# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [112]:
# Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 
#   Replace all the elements in the third column with 1.
import numpy as np
ass1 = np.random.randint(1,20,size=(5,5))
ass1[:,2] = 0
print(ass1)

ass1 = np.random.randint(1, 10, size=(5, 4))
padded_ass1 = np.pad(([0,1,1],[0,1,1]), ((1, 0), (0, 1)),  constant_values=0)
print(padded_ass1)


# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

as1qs2 = np.random.randint(1,16,size=(4,4))
np.fill_diagonal(as1qs2,0)
as1qs2

[[ 6 14  0  8  9]
 [ 6 17  0  7 13]
 [18  9  0  4 19]
 [10 10  0 16 11]
 [ 1 17  0  6 17]]
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]]


array([[ 0,  7,  9, 12],
       [11,  0, 15, 14],
       [ 5,  7,  0, 15],
       [11, 10,  7,  0]])

Assignment 2: Array Indexing and Slicing


In [134]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns

as2qs1 = np.arange(1,37)
as2qs1= as2qs1.reshape(6,6)
print(as2qs1.reshape(6,6))
as2qs1[2:5,1:4]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [214]:
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
as2qs2 = np.random.randint(1,26,size=(5,5))
print(as2qs2)
as2qs2[-1]

np.concatenate(([1,2,3],[2,3]))

[[ 8 21 18 17  5]
 [ 7 25 15 21 16]
 [21 19 24  3  7]
 [15  7 13 20  7]
 [19 15  2  5 18]]


array([1, 2, 3, 2, 3])

In [227]:
nparray = np.array([[1, 2, 3], [11, 22, 33]])
 
nparray = np.sum(nparray, axis=1)
nparray

array([ 6, 66])