In [ ]:
import numpy as np


# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1
arr1 = np.random.randint(1,20,size=(5,5))
print("Orginal Array :\n",arr1)
arr1[0:,2] = 1
arr1

Orginal Array :
 [[14 11  8  8  6]
 [15 13 12 13  6]
 [19  7 16  1 17]
 [ 3 16 12  5 17]
 [ 6  5  4  6  1]]


array([[14, 11,  1,  8,  6],
       [15, 13,  1, 13,  6],
       [19,  7,  1,  1, 17],
       [ 3, 16,  1,  5, 17],
       [ 6,  5,  1,  6,  1]])